version: '3'
services:
  #授权服务
  mosbrh_gateway:
    image: registry.cn-shenzhen.aliyuncs.com/mosbrhblog/mosbrh_gateway:latest
    container_name: mosbrh_gateway
    restart: always
    ports:
      - 8607:8607
    networks:
      - mosbrh
    environment:
      - COMPOSE_PROJECT_NAME=mosbrh_gateway
    volumes:
    - ../log/:/logs/
    - ../config/mosbrh_gateway/:/config/
networks:
  mosbrh:
    external: true
