version: '3'
services:
  #授权服务
  vue_mosbrh_web:
    image: registry.cn-shenzhen.aliyuncs.com/mosbrhblog/vue_mosbrh_web:latest
    container_name: vue_mosbrh_web
    restart: always
    ports:
      - 9527:80
    networks:
      - mosbrh
    env_file:
      - ../config/vue_mosbrh_web.env
    environment:
      - COMPOSE_PROJECT_NAME=vue_mosbrh_web
networks:
  mosbrh:
    external: true
