version: '3'
services:
  #授权服务
  vue_mosbrh_admin:
    image: registry.cn-shenzhen.aliyuncs.com/mosbrhblog/vue_mosbrh_admin:latest
    container_name: vue_mosbrh_admin
    restart: always
    ports:
      - 9528:80
    networks:
      - mosbrh
    env_file:
      - ../config/vue_mosbrh_admin.env
    environment:
      - COMPOSE_PROJECT_NAME=vue_mosbrh_admin

networks:
  mosbrh:
    external: true
