# ============================== Filebeat inputs ===============================

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - ../../../log/mosbrh-web/*.log
    fields:
      docType: mosbrh_web-log
      project: mosbrh_web
      from: mosbrh_web
    fields_under_root: true
    multiline:
      pattern: '^\[mosbrh-web:[\d\.:]+\]'
      negate: true
      match: after
      timeout: 2s
  - type: log
    enabled: true
    paths:
      - ../../../log/mosbrh-admin/*.log
    fields:
      docType: mosbrh_admin-log
      project: mosbrh_admin
      from: mosbrh_admin
    fields_under_root: true
    multiline:
      pattern: '^\[mosbrh-admin:[\d\.:]+\]'
      negate: true
      match: after
      timeout: 2s
  - type: log
    enabled: true
    paths:
      - ../../../log/mosbrh-sms/*.log
    fields:
      docType: mosbrh_sms-log
      project: mosbrh_sms
      from: mosbrh_sms
    fields_under_root: true
    multiline:
      pattern: '^\[mosbrh-sms:[\d\.:]+\]'
      negate: true
      match: after
      timeout: 2s
  - type: log
    enabled: true
    paths:
      - ../../../log/mosbrh-picture/*.log
    fields:
      docType: mosbrh_picture-log
      project: mosbrh_picture
      from: mosbrh_picture
    fields_under_root: true
    multiline:
      pattern: '^\[mosbrh-picture:[\d\.:]+\]'
      negate: true
      match: after
      timeout: 2s
  - type: log
    enabled: true
    paths:
      - ../../../log/mosbrh-gateway/*.log
    fields:
      docType: mosbrh_gateway-log
      project: mosbrh_gateway
      from: mosbrh_gateway
    fields_under_root: true
    multiline:
      pattern: '^\[mosbrh-gateway:[\d\.:]+\]'
      negate: true
      match: after
      timeout: 2s
  - type: log
    enabled: true
    paths:
      - ../../../log/mosbrh-monitor/*.log
    fields:
      docType: mosbrh_monitor-log
      project: mosbrh_monitor
      from: mosbrh_monitor
    fields_under_root: true
    multiline:
      pattern: '^\[mosbrh-monitor:[\d\.:]+\]'
      negate: true
      match: after
      timeout: 2s
  - type: log
    enabled: true
    paths:
      - ../../../log/mosbrh-search/*.log
    fields:
      docType: mosbrh_search-log
      project: mosbrh_search
      from: mosbrh_search
    fields_under_root: true
    pipeline: mosbrh-log
    multiline:
      pattern: '^\[mosbrh-search:[\d\.:]+\]'
      negate: true
      match: after
      timeout: 2s


# ============================== Filebeat modules ==============================

filebeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: false

  # Period on which files under path should be checked for changes
  #reload.period: 10s

# ======================= Elasticsearch template setting =======================

setup.template.settings:
  index.number_of_shards: 1
  #index.codec: best_compression
  #_source.enabled: false

# =================================== Kibana ===================================

# Starting with Beats version 6.0.0, the dashboards are loaded via the Kibana API.
# This requires a Kibana endpoint configuration.
setup.kibana:

# ---------------------------- Elasticsearch Output ----------------------------
# output.elasticsearch:
# Array of hosts to connect to.
# hosts: ["192.168.163.128:9200"]
# bulk_max_size: 2048

# ------------------------------ Logstash Output -------------------------------
output.logstash:
  # The Logstash hosts
  hosts: ["elk:5044"]
  bulk_max_size: 2048

# ================================= Processors =================================
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~